CA: Qz2zDuRaq2LhuYN94sGN8ebn4unZhxAogh34hpZpump
description: go in for a wock
imagelink: https://pbs.twimg.com/media/GSVVEUkXIAAdUYt?format=jpg&name=large
paragraph1: "He\xE2\u20AC\u2122s not just walkin, he\xE2\u20AC\u2122s going in for\
  \ a wock. Imagine swagger so intense it leaves prints of pure skibidi rizz. He\xE2\
  \u20AC\u2122s out there, banging music, on a mission to turn the ordinary into the\
  \ extraordinary. It\xE2\u20AC\u2122s not just a stroll; it\xE2\u20AC\u2122s a bombastic\
  \ statement."
paragraph2: wock wock wock!
paragraph3: money money money
title: On Wock
year: 2024
